### ISSUE TITLE
textconf -> textconv?

### ISSUE THREAD

**Issue by michaelblyons** [alikins/gitconfig#6]
Are these typos?

https://github.com/alikins/gitconfig/blob/ca1afb7d46e63af4866b6fa2f36d0683e6cd83a7/gitconfig#L70-L73

(I stumbled across your repo while looking for `xfuncname` samples.)

**Comment by alikins** [comment]
@michaelblyons Yeah, must be a typo. Should be `textconv`.  I suspect I didn't notice because I also set svg attributes to 'binary' (https://github.com/alikins/gitconfig/blob/master/gitattributes#L17-L20) so the `[diff "svg"]` config isnt used.
